GET http://localhost:5073/games
###
GET http://localhost:5073/games/4
###
POST http://localhost:5073/games
Content-Type: application/json 


{
    "Name":"omares",
    "Genre":"familyUse",
    "Price":"21.22",
    "ReleaseDate":"2010-10-15"
}
###
PUT http://localhost:5073/games/4
Content-Type: application/json


{
    
   "Name":"omareCCDs",
    "Genre":"familyUse",
    "Price":"77.22",
    "ReleaseDate":"2010-10-15"
}

###
DELETE http://localhost:5073/games/2